### ISSUE TITLE
[Feature Request]: Integration with cert-manager 1.10

### ISSUE THREAD

**Issue by scottd018** [cert-manager/aws-privateca-issuer#229]
### Describe why this change is needed

It appears that the AWS PCA Issuer integration with cert-manager version 1.10 does not quite work.  After upgrading to cert-manager 1.10 and attempting to use the latest version of AWS PCA Cluster Issuer resources, these are the messages I see (this works with cert-manager 1.9.1):

```
E1121 15:03:27.073943       1 checks.go:55] cert-manager/controller/certificaterequests-issuer-selfsigned/handleSecretReference "msg"="failed to determine affected certificate requests" "error"="invalid value \"AWSPCAClusterIssuer\" for issuerRef.kind. Must be empty, \"Issuer\" or \"ClusterIssuer\"" "resource_kind"="Secret" "resource_name"="external-secrets-webhook" "resource_namespace"="my-platform" "resource_version"="v1"
```

Key thing to point out is `"error"="invalid value \"AWSPCAClusterIssuer\" for issuerRef.kind. Must be empty, \"Issuer\" or \"ClusterIssuer\""`.

Here is my certificate definition:

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-cert
  namespace: my-platform
spec:
  commonName: external-secrets-webhook.my-platform.svc
  dnsNames:
    - external-secrets-webhook.my-platform.svc
    - external-secrets-webhook
    - external-secrets-webhook.svc.cluster.local
    - external-secrets-webhook.cluster.local
    - localhost
  duration: 2160h0m0s
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    kind: ClusterIssuer
    name: intermediate-ca
  renewBefore: 360h0m0s
  secretName: external-secrets-webhook
```

And my ClusterIssuer/AWS PCA ClusterIssuer:

```
---
apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  name: root-ca
spec:
  arn: REDACTED
  region: us-gov-west-1
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: intermediate-ca
  namespace: my-platform
spec:
  commonName: intermediate-ca
  duration: 2160h0m0s
  isCA: true
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: root-ca
  renewBefore: 360h0m0s
  secretName: intermediate-ca
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: intermediate-ca
spec:
  ca:
    secretName: intermediate-ca
```

### Is there anything else you would like to add?

Looking for some guidance to see if this has been tested with 1.10.
