### ISSUE TITLE
[Bug]: Certificate not showing in shared AWS account

### ISSUE THREAD

**Issue by patpicos** [cert-manager/aws-privateca-issuer#342]
### Describe the expected outcome

Env Details: AWS Private CA is in a central account and shared with other AWS accounts.

I created the following certificate on a cluster with cert-manager.  The certificate was created and the secret was also generated. I validated with openssl that the cert is good.
```yaml
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: cert-mgr-test
spec:
  commonName: cert-mgr-test.cicd.dev.aws.blah.net
  dnsNames:
    - cert-mgr-test.cicd.dev.blah.net
  duration: 2160h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: aws-pca
  renewBefore: 360h0m0s
  secretName: cert-mgr-test
  usages:
    - server auth
    - client auth

```

```yaml
apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cert-mgr-test-pca-config:awspca.cert-manager.io/AWSPCAClusterIssuer:samsung-vcu/aws-pca
  generation: 1
  name: aws-pca
  resourceVersion: "26581"
  uid: f0aa2e8a-6eae-43b9-b6ad-47358f82166b
spec:
  arn: arn:aws:acm-pca:us-west-2:xxx-central-account-id:certificate-authority/c3c79434-a242-47a6-9a25-cc8325340d1c
  region: us-west-2
status:
  conditions:
  - lastTransitionTime: "2024-10-02T19:48:56Z"
    message: Issuer verified
    reason: Verified
    status: "True"
    type: Ready
```
```
k get CertificateRequest  -A                                                                                                                                                                                                           
NAMESPACE      NAME              APPROVED   DENIED   READY   ISSUER    REQUESTOR                                         AGE
cert-manager   cert-mgr-test-1   True                True    aws-pca   system:serviceaccount:cert-manager:cert-manager   115m
```
When i look in my account under `[AWS Certificate Manager] --> Certificates`, i think the cert should show there

### Describe the actual outcome

i dont see the certificate listed.

### Steps to reproduce

_No response_

### Relevant log output

```shell
{"level":"info","ts":"2024-10-03T15:02:21Z","logger":"controllers.CertificateRequest","msg":"Created certificate with arn: arn:aws:acm-pca:us-west-2:xxx-central-account-id:certificate-authority/c3c79434-a242-47a6-9a25-cc8325340d1c/certificate/a205075ebed9132b98b90e9f215f7548","certificaterequest":{"name":"cert-mgr-test-1","namespace":"cert-manager"}}
```


### Version

                targetRevision: "1.15.3"
                chart: cert-manager
                targetRevision: "1.3.0"
                chart: aws-privateca-issuer

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Other

### Severity

Severity 3
