### ISSUE TITLE
issuer fails to validate

### ISSUE THREAD

**Issue by williamcodes** [cert-manager/aws-privateca-issuer#46]
Any idea why the issuer would never validate?

Here are my manifests:
```yaml
apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAIssuer
metadata:
  name: awspcaissuer
  namespace: cert-manager
spec:
  arn: {{ .Values.pcaArn }}
  region: {{ .Values.region }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
```

Here are the values I passed to the aws-pricateca-issuer helm chart and cert-manager helm chart:
```yaml
cert-manager:
  installCRDs: true
  serviceAccount:
    create: false
    name: cert-manager
aws-privateca-issuer:
  serviceAccount:
    create: false
    name: cert-manager
```

Here's the output when I try to describe the issuer:
```
$ kubectl describe -n cert-manager awspcaissuers.awspca.cert-manager.io

Name:         awspcaissuer
Namespace:    cert-manager
Labels:       argocd.argoproj.io/instance=cert-manager
Annotations:  <none>
API Version:  awspca.cert-manager.io/v1beta1
Kind:         AWSPCAIssuer
Metadata:
  Creation Timestamp:  2021-08-03T14:23:45Z
  Generation:          1
  Managed Fields:
    API Version:  awspca.cert-manager.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:argocd.argoproj.io/instance:
      f:spec:
        .:
        f:arn:
        f:region:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2021-08-03T14:23:45Z
  Resource Version:  45566948
  Self Link:         /apis/awspca.cert-manager.io/v1beta1/namespaces/cert-manager/awspcaissuers/awspcaissuer
  UID:               d5a200ab-0ff9-4f77-858d-1d6e89c2b0f7
Spec:
  Arn:     arn:aws:acm-pca:us-east-1:734116470960:certificate-authority/3c01fb76-eced-49a2-8076-3bf2110807a0
  Region:  us-east-1
Events:    <none>
```
You'll see no events ever fire, including the one where the issuer is validated.

Here's my certificate:
```
$ kubectl describe -A certificate
Name:         cms-devops
Namespace:    default
Labels:       argocd.argoproj.io/instance=cms-devops
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2021-08-03T13:09:57Z
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:argocd.argoproj.io/instance:
      f:spec:
        .:
        f:commonName:
        f:dnsNames:
        f:duration:
        f:issuerRef:
          .:
          f:group:
          f:kind:
          f:name:
        f:privateKey:
          .:
          f:algorithm:
          f:size:
        f:renewBefore:
        f:secretName:
        f:usages:
    Manager:      argocd-application-controller
    Operation:    Update
    Time:         2021-08-03T13:09:57Z
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:lastFailureTime:
    Manager:         controller
    Operation:       Update
    Time:            2021-08-03T14:09:59Z
  Resource Version:  45559101
  Self Link:         /apis/cert-manager.io/v1/namespaces/default/certificates/cms-devops
  UID:               884b894b-acf8-4136-8075-d0719934055b
Spec:
  Common Name:  cms-devops.william-sandbox.internal
  Dns Names:
    cms-devops.william-sandbox.internal
  Duration:  2160h0m0s
  Issuer Ref:
    Group:  awspca.cert-manager.io
    Kind:   AWSPCAClusterIssuer
    Name:   root-ca
  Private Key:
    Algorithm:   RSA
    Size:        2048
  Renew Before:  360h0m0s
  Secret Name:   cms-devops-tls-app-secret
  Usages:
    server auth
    client auth
Status:
  Conditions:
    Last Transition Time:  2021-08-03T14:09:59Z
    Message:               The certificate request has failed to complete and will be retried: issuer is not ready
    Observed Generation:   1
    Reason:                Failed
    Status:                False
    Type:                  Issuing
    Last Transition Time:  2021-08-03T13:09:57Z
    Message:               Issuing certificate as Secret does not exist
    Observed Generation:   1
    Reason:                DoesNotExist
    Status:                False
    Type:                  Ready
  Last Failure Time:       2021-08-03T14:09:59Z
Events:
  Type     Reason     Age                From          Message
  ----     ------     ----               ----          -------
  Normal   Issuing    36m (x2 over 96m)  cert-manager  Issuing certificate as Secret does not exist
  Warning  Failed     36m (x2 over 96m)  cert-manager  The certificate request has failed to complete and will be retried: issuer is not ready
  Normal   Generated  36m                cert-manager  Stored new private key in temporary Secret resource "cms-devops-pj7gp"
  Normal   Requested  36m                cert-manager  Created new CertificateRequest resource "cms-devops-2dfh5"
```

You can see that the the certificate never completes because the issuer is not ready. Is something misconfigured?
